# Welcome to Jekyll!
#

# Site settings
title: Backcountry Wok
description: |
  Dehydrated asian camping meals <br>
  with an environmental conscience  

owner: Backcountry Wok
first_published: 2017 # if migrating another site, the year of your first publish
email: ceo@backcountrywok.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.backcountrywok.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/backcountry_wok
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: ceo@backcountrywok.com
  #flickr:
  instagram: https://www.instagram.com/backcountry_wok/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
plugins:
  - jekyll-analytics
jekyll-analytics:
  GoogleAnalytics:
    id: UA-106765418-1
    anonymizeIp: false